[build-system]
requires = ["scikit-build-core>=0.10", "pybind11>=2.13"]
build-backend = "scikit_build_core.build"

[project]
name = "diffvg-mlx"
version = "0.0.1"
description = "Differentiable Vector Graphics for MLX"
readme = "README.md"
requires-python = ">=3.10"
license = { file = "LICENSE" }
dependencies = [
    "mlx",
    "numpy",
    "svgpathtools",
    "scikit-image",
    "cssutils",
]

[tool.scikit-build]
cmake.build-type = "Release"
wheel.packages = ["pydiffvg"]
